# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  all-tests-job:
    docker:
      - image: cimg/python:3.12.3

    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "poetry.lock" }}
      - run:
          name: "install dependencies"
          command: poetry install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "poetry.lock" }}
          paths:
            - env
      - run:
          name: "Unit tests"
          command: "poetry run pytest"
      - run:
          name: "Linting check"
          command: "poetry run ruff check"
      - run:
          name: "Format check"
          command: "poetry run ruff format --check"
      - run:
          name: "Integration tests"
          # These commands load our application credentials from the service account
          # So that we can run the integration tests.
          # See https://cloud.google.com/docs/authentication/production
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcp.json"
            echo "$GCLOUD_SERVICE_KEY" > "$GOOGLE_APPLICATION_CREDENTIALS"
            poetry run pytest -m integration
      - run:
          name: "Install and Configure outerbounds"
          command: |
            poetry run outerbounds service-principal-configure \
            --name mozmlops-ci \
            --deployment-domain desertowl.obp.outerbounds.com \
            --perimeter default \
            --jwt-token $CIRCLE_OIDC_TOKEN_V2
      - run:
          name: "Run a flow"
          command: |
            cd src/mozmlops/templates
            poetry run python template_flow.py --no-pylint run 


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  # This is the name of the workflow, feel free to change it to better match your workflow.
  pre-merge-workflow:
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - all-tests-job:
          # Provides environment variables needed to integrate with GCS for integration tests
         context: data-eng-circleci-tests
  nightly-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - all-tests-job:
          # Provides environment variables needed to integrate with GCS for integration tests
         context: data-eng-circleci-tests

